### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by monreal** [h4mu/rott94#1]
I was very happy to finally find an SDL2-port of ROTT. It compiled without a problem on my Fedora 26 desktop, however when running it with the same game data I previously used the icculus.org ROTT with, I get this:

./rott-rottcd 
Rise of the Triad Startup  Version 1.4
 CD Version 
Z_INIT: 8950000 bytes
OH NO OH NO ROTT CRASHED!

Any idea what could be wrong?

**Comment by h4mu** [comment]
Hi, it's hard to tell from the information you provided but make sure the game data is in the "assets" subfolder. Also note that 64 bit platforms are not supported at the moment so you may need to install multilib gcc and 32 bit SDL2 libraries and force 32 bit compilation. You can force 32 bit compilation by using the "-m32" compiler flag like this:
make CFLAGS="-m32"

**Comment by monreal** [comment]
Thanks for the information. After forcing the 32-bit compile (make CFLAGS="-m32 -O2 -I/usr/include/SDL2 -D_REENTRANT" rott-rottsite) and moving the data (which I got from Steam, btw) to the assets/ directory I got a message about a missing buttons.bmp. I found it in the assets/ directory in GIT. After moving it to the directory my executable is in, everything works fine. Thanks!

**Comment by h4mu** [comment]
Hi, I also managed to fix 64 bit compatibility.

**Comment by monreal** [comment]
Great, however I cannot compile latest master. Will open a new issue...
