### ISSUE TITLE
Request: Please Port This to Windows 10

### ISSUE THREAD

**Issue by MasterO2** [h4mu/rott94#12]
Please port rott94 to Windows 10 itself.  All the other Windows sourceports for ROTT are fair to poor, with lots of bugs, especially WinRottGL.

**Comment by h4mu** [comment]
See latest release. Unfortunately I haven't been able to make sound effects work but music is working.

**Comment by MasterO2** [comment]
> 
> 
> See latest release. Unfortunately I haven't been able to make sound effects work but music is working.

Question: For the GOG release of Rise of the Triad: Dark War, which one do I use?

Rott94.Windows.Release.CDROM.files or Rott94.Windows.Release.files
