### ISSUE TITLE
Intro movie black

### ISSUE THREAD

**Issue by monreal** [h4mu/rott94#2]
The intro movie (after starting a game) stays black. I hear the sound but I cannot see anything.

**Comment by h4mu** [comment]
I can confirm it's the same for me and I don't remember ever seeing it work before but it didn't bother me that much tbh. I haven't looked for the cause yet and I probably won't have much time for it anytime soon but if you find a fix please create a pull request.

**Comment by h4mu** [comment]
FIxed in latest commit, palettes work differently in SDL (and modern graphics libraries) than in good old DOS.
