### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by monreal** [h4mu/rott94#5]
With current master head:

cc -g -O0 -Wall -I/usr/include/SDL2 -D_REENTRANT   cin_actr.o cin_efct.o cin_evnt.o cin_glob.o cin_main.o cin_util.o dosutil.o engine.o isr.o modexlib.o rt_actor.o rt_battl.o rt_build.o rt_cfg.o rt_crc.o rt_com.o rt_debug.o rt_dmand.o rt_door.o rt_draw.o rt_floor.o rt_game.o rt_in.o rt_main.o rt_map.o rt_menu.o rt_msg.o rt_net.o rt_playr.o rt_rand.o rt_scale.o rt_sound.o rt_spbal.o rt_sqrt.o rt_stat.o rt_state.o rt_str.o rt_swift.o rt_ted.o rt_util.o rt_view.o rt_vid.o rt_err.o scriplib.o w_wad.o watcom.o z_zone.o byteordr.o dukemusc.o winrott.o audiolib/audiolib.a -lSDL2 -lSDL2_mixer -lm  -o rott-rottsite
/usr/bin/ld: audiolib/audiolib.a(multivoc.o): in function `MV_SetVoicePitch':
/home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:1347: undefined reference to `PITCH_GetScale'
/usr/bin/ld: /home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:1347: undefined reference to `PITCH_GetScale'
/usr/bin/ld: /home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:1347: undefined reference to `PITCH_GetScale'
/usr/bin/ld: /home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:1347: undefined reference to `PITCH_GetScale'
/usr/bin/ld: /home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:1347: undefined reference to `PITCH_GetScale'
/usr/bin/ld: audiolib/audiolib.a(multivoc.o):/home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:2755: more undefined references to `PITCH_GetScale' follow
/usr/bin/ld: audiolib/audiolib.a(multivoc.o): in function `MV_UnlockMemory':
/home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:3430: undefined reference to `PITCH_UnlockMemory'
/usr/bin/ld: audiolib/audiolib.a(multivoc.o): in function `MV_LockMemory':
/home/micmon/code/gaming/rott94.git/rott/audiolib/multivoc.c:3533: undefined reference to `PITCH_LockMemory'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:92: rott-rottcd] Error 1
make[1]: Leaving directory '/home/micmon/code/gaming/rott94.git/rott'
make: *** [Makefile:22: rott-rottcd] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/micmon/code/gaming/rott94.git/rott'
mv rott/rott-huntbgin .
make[1]: Leaving directory '/home/micmon/code/gaming/rott94.git/rott'
mv rott/rott-darkwar .
make[1]: Leaving directory '/home/micmon/code/gaming/rott94.git/rott'
mv rott/rott-rottsite .

**Comment by h4mu** [comment]
Did you try to re-run make after the error? Are you sure you have the whole source code? The missing references are implemented in the pitch.c file in the same folder so can you check if you have a pitch.c and pitch.o files in the audiolib folder?

**Comment by monreal** [comment]
After running make again I can no longer reproduce the problem.
